urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.defaults import *

handler500 = 'djangotoolbox.errorviews.server_error'

urlpatterns = patterns('',
    (r'^image_polling/', include('main.urls')),
    ('^_ah/warmup$', 'djangoappengine.views.warmup'),
    url(r'^vote_or_die/$', 'django.views.generic.simple.direct_to_template',
        {'template':'vote_or_die.html'}, name='vote_campaign'),
    url(r'^about/$', 'django.views.generic.simple.direct_to_template',
        {'template':'about.html'}, name='about'),
    # for google webmasters verification.
    url(r'^googlebfe22224fa5be37c.html$', 'django.views.generic.simple.direct_to_template',
        {'template':'googlebfe22224fa5be37c.html'}),
    # robots.txt
    url(r'^robots.txt$', 'django.views.generic.simple.direct_to_template',
        {'template':'robots.txt'}, name='robots.txt'),
    (r'^$', include('main.urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User
from djangotoolbox import fields

# Create your models here.
# TODO(rafi): This is a bad implementation..if you are using datastore..


class UserImage(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    image = models.FileField(upload_to='uploads/user_images')
    question = models.CharField(max_length=300, null=True, blank=True)
    created_date = models.DateField(auto_now_add=True)


class Options(models.Model):
    poll_id = models.ForeignKey(UserImage)
    option_name = models.CharField(max_length=100)
    # coordinates comprise of x1,y1,width,height
    coordinates = models.CharField(max_length=50)
    users = fields.ListField(null=True, blank=True)
    votes = models.IntegerField()


class VotingHistory(models.Model):
    poll = models.ForeignKey(UserImage)
    option_id = models.ForeignKey(Options)
    user = models.ForeignKey(User, null=True, blank=True)
    ip_address = models.CharField(max_length=15, null=True, blank=True)
    created_date = models.DateField(auto_now_add=True)

    class Meta:
        #FIXME: this prolly has no effect on app-engine.
        unique_together = (('option_id', 'user', 'ip_address'),)

templates/about.html
{%extends 'poll_base.html' %}
{%block title%}About{%endblock%}
{%block body %}
<div style="font-size:100%">
  <div style="text-align:left; width:800px; margin: 0 auto;"><h4>About PicPoll.in (picpollin')</h4><br/>
    PicPoll.in is the site where you can create and share your own polls with a pic.<br/>
    All this as anonymous:)<br/>
    Apart of the fun associated with it you can also show it to your boss and get promoted.<br/>
    <br/>
    <br/>
    <h4>About the author</h4><br/>
    I am a a developer, a music lover and have a pathetic sense of humour. I enjoy wasting my time with my friends.<br/>
    <br/>
    If you have any bugs or suggestions you can contact me on <a href="mailto:confessin@gmail.com">confessin@gmail.com</a>
    Soon I will be updating a bug tracker for this
    
    I will just leave it there if you want to contact me for the awesome i am destined to have(without a boss)<br/>
    <!-- Facebook Badge START --><a href="http://www.facebook.com/rafi.was.not.available" target="_TOP" style="font-family: &quot;lucida grande&quot;,tahoma,verdana,arial,sans-serif; font-size: 11px; font-variant: normal; font-style: normal; font-weight: normal; color: #3B5998; text-decoration: none;" title="Mohammad Rafi">Mohammad Rafi</a><br/><a href="http://www.facebook.com/rafi.was.not.available" target="_TOP" title="Mohammad Rafi"><img src="http://badge.facebook.com/badge/707845280.6356.98757742.png" style="border: 0px;" /></a><br/><a href="http://www.facebook.com/badges/" target="_TOP" style="font-family: &quot;lucida grande&quot;,tahoma,verdana,arial,sans-serif; font-size: 11px; font-variant: normal; font-style: normal; font-weight: normal; color: #3B5998; text-decoration: none;" title="Make your own badge!">Create Your Badge</a><!-- Facebook Badge END -->
    <br/>
    <br/>
    <img src="{{MEDIA_URL}}images/the_end.jpg">

    <pre>
    #TODO:
    Better facebook integration(with an ability to poll results as well
    make it work on IE(Bleh)
    change the share butttons(write your own)
    SEO
    </pre>

  </div>
{%endblock%}

templates/base.html
<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    dir="{% if LANGUAGE_BIDI %}rtl{% else %}ltr{% endif %}"
    xml:lang="{% firstof LANGUAGE_CODE 'en' %}"
    lang="{% firstof LANGUAGE_CODE 'en' %}">
  <head>
    <title>{% block title %}{% endblock %} - Nonrel-testapp</title>

    {% block css %}
    {% endblock %}

    {% block preload_js %}
    {% endblock %}

    {% block extra-head %}{% endblock %}
  </head>

  <body>
    <div id="header">
      <a id="logo" href="/">Nonrel-testapp</a>
    </div>

    <div class="columns">
      <div id="content" class="column">
        {% block content-header %}
          {% if error %}<div class="error">{{ error }}</div>{% endif %}
          {% if info %}<div class="info">{{ info }}</div>{% endif %}
          {% if messages %}
            {% for message in messages %}
              <div class="info">{{ message }}</div>
            {% endfor %}
          {% endif %}
        {% endblock %}

        {% block content %}{% endblock %}
      </div>

      <div id="sidebar" class="column">
        {% block sidebar %}
        {% endblock %}
      </div>
    </div>

    <div id="footer">
      <p>Powered by <a href="http://www.allbuttonspressed.com/projects/django-nonrel">Django-nonrel</a></p>
    </div>

    {% block js %}
    {% endblock %}
  </body>
</html>

templates/googlebfe22224fa5be37c.html
google-site-verification: googlebfe22224fa5be37c.html

templates/home.html
{% extends 'base.html' %}
{% block title %}It works!{% endblock %}

{% block content %}
<h1>It works!</h1>
<p>
Your Django-nonrel installation is working fine.
Now go and build something useful with it. :)
</p>

<p>
Also, make sure you follow the
<a href="http://www.allbuttonspressed.com/blog/django">Django-nonrel &amp; webdev blog</a>,
so you don't miss any new features and improvements.
</p>

<p>
If you're new to Django you should take a look at the
<a href="http://docs.djangoproject.com/en/dev/">Django documentation</a>
and the
<a href="http://www.djangobook.com/">Django book</a>.
You'll also find <a href="http://djangosnippets.org/">djangosnippets</a>
very useful.
</p>

<p>
If you search for reusable apps that work with Django-nonrel here's a list to get you started:
</p>

<ul>
  <li><a href="http://www.allbuttonspressed.com/projects/django-mediagenerator">django-mediagenerator</a>: Combines and compresses your JS and CSS files</li>
  <li><a href="http://www.allbuttonspressed.com/projects/django-dbindexer">django-dbindexer</a>: Adds extra DB features (e.g., __iexact, JOINs, etc.) beyond the native DB API</li>
  <li><a href="http://www.allbuttonspressed.com/projects/nonrel-search">nonrel-search</a>: A simple full-text search engine for App Engine and other non-relational DBs</li>
  <li><a href="http://www.allbuttonspressed.com/projects/django-filetransfers">django-filetransfers</a>: Generic API for file uploads/downloads (e.g. via App Engine Blobstore)</li>
  <li><a href="http://www.allbuttonspressed.com/projects/allbuttonspressed">allbuttonspressed</a>: The simple CMS/blog that powers the <a href="http://www.allbuttonspressed.com">Django-nonrel website</a></li>
  <li><a href="http://www.allbuttonspressed.com/projects">...and our other projects...</a></li>
</ul>

<p>
Finally, take a look at the apps listed on <a href="http://djangopackages.com/">Django Packages</a>. Many simple Django apps (e.g., <a href="https://bitbucket.org/ubernostrum/django-registration">django-registration</a>) should work unmodified. If you want to use <a href="http://robhudson.github.com/django-debug-toolbar/">django-debug-toolbar</a> you need to disable the SQLDebugPanel in your settings.
</p>
{% endblock %}

templates/index.html
{%extends 'poll_base.html' %}
{%block title%}Home{%endblock%}
{%block preload_js %}
  <script type="text/javascript" src="{{MEDIA_URL}}javascript/jquery_003.js"></script>
  <script type="text/javascript" src="{{MEDIA_URL}}javascript/jquery-1.6.2.min.js"></script>
  <script type="text/javascript" src="{{MEDIA_URL}}javascript/jquery-ui-1.8.16.custom.min.js"></script>
  <script type="text/javascript" src="{{MEDIA_URL}}javascript/jquery.js"></script>
  <script type="text/javascript" src="{{MEDIA_URL}}javascript/jquery_002.js"></script>

  <script type="text/javascript">

     //{'1':{"x1":"10","y1":"10","height":"150","width":"50","note":"This is a note"},
      //'2':{"x1":"25","y1":"25","height":"70","width":"80","note":"<b>This</b> is a new note This is another note This is a new note"}};

    $(window).load(function () {
      notes = {};
      //$('#tern').imgNotes(); //If your notes data is is not named notes pass it

      // jQuery UI Dialog
      $('#dialog').dialog({
          autoOpen: false,
          width: 400,
          modal: true,
          resizable: false,
          buttons: {
              "Yeah": function() {
                  var target = $($(this).data('target'));
                  // FIXME: we might have to send notes data
                  // to store options in backend..fix the implementation.
                  delete notes[target[0].id]
                  target.remove()
                  $(this).dialog("close");
              },
              "Nope": function() {
                  $(this).dialog("close");
              }
          }
      });

      //$('#tern').imgAreaSelect({ onSelectChange: showaddnote })

      $('#cancelnote').click(function(){
        $('#tern').imgAreaSelect({ hide: true, disable:true });
        $('#noteform').hide();
      });

      $('#addnotelink').click(function(){
        $('#tern').imgAreaSelect({ enable:true, onSelectChange: showaddnote, x1: 120, y1: 90, x2: 280, y2: 210 });
        return false;
      });

      $('#tern').dblclick(function(){
        $('#tern').imgAreaSelect({ enable:true, onSelectChange: showaddnote, x1: 120, y1: 90, x2: 280, y2: 210 });
        return false;
      });

      // Adding the note
      $('#NoteAddForm').submit(function(){
        formObj = $('#NoteAddForm')[0]
        var note_length = Object.keys(notes).length;
        notes[note_length+1] = {"x1":formObj.NoteX1.value,"y1":formObj.NoteY1.value,"height":formObj.NoteHeight.value,"width":formObj.NoteWidth.value,"note":formObj.NoteNote.value};
        //clear all the present tags
        $('.note').remove();
        $('.notep').remove()
        $('#tern').imgNotes(notes, 'edit')
        $('#tern').imgAreaSelect({ hide: true, disable:true });
        $('#noteform').hide()
        return false;
      });
        /*$('div.note').dblclick(function(e){
        var target = e.target
        $("p#dialog-email").html($("input#emailJQ").val());
        $('#dialog').data("target", target).dialog('open');
      });*/
      /*$('#imageForm').submit(function(){
          $.post('upload_image',$("#imageForm").serialize(),
            function(data) {
            //$("#user-img").html(data)
            $('.result').html(data);
            });
          return false;
          });
          */
      $('#imageForm').ajaxForm(function(data) {
          $('.result').html(data);
          return false;
      });
  });
  // event handler for the note
  function showDeleteNote(noteObj){
    $("p#dialog-email").html($("input#emailJQ").val());
    $('#dialog').data("target", noteObj).dialog('open');
  };

  function showaddnote (img, area) {
    imgOffset = $(img).offset();
    form_left  = parseInt(imgOffset.left) + parseInt(area.x1);
    form_top   = parseInt(imgOffset.top) + parseInt(area.y1) + parseInt(area.height)+5;

    $('#noteform').css({ left: form_left + 'px', top: form_top + 'px'});

    $('#noteform').show();

    $('#noteform').css("z-index", 10000);
    $('#NoteX1').val(area.x1);
    $('#NoteY1').val(area.y1);
    $('#NoteHeight').val(area.height);
    $('#NoteWidth').val(area.width);
  }
  </script>
{%endblock preload_js %}
{%block body%}
<div style="padding-bottom:30px; border-bottom: 1px solid #DEDEDE;" >
    <div>
      <form id="imageForm" method="post" action="{{ upload_url }}" enctype="multipart/form-data">
        {%csrf_token%}
        <div class="input_image"><h2>Upload an image to create your own poll</h2></div>
        <br/>
        <div>{{ form }}</div>
        </br>
        <div>  <button>Upload</button>
        </div>
      </form>
    </div>
    </div>
    <div style="left: 547px; top: 223px; display: none; z-index: 10000;" id="noteform">
      <form id="NoteAddForm" method="post" action="">
        <fieldset>
        <legend>Add Note</legend>
        <input name="data[Note][x1]" value="120" id="NoteX1" type="hidden">
        <input name="data[Note][y1]" value="90" id="NoteY1" type="hidden">
        <input name="data[Note][height]" value="120" id="NoteHeight" type="hidden">
        <input name="data[Note][width]" value="160" id="NoteWidth" type="hidden">
        <textarea name="data[Note][note]" id="NoteNote"></textarea>
        </fieldset>
        <div class="submit"><input value="Submit" type="submit"> &nbsp;&nbsp;&nbsp;<input value="Cancel" id="cancelnote" type="button"></div>
      </form>
    </div>
    <div id "result" class="result"></div>

    <div id="dialog" title="Option Deleter says">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 0 0;"></span>Shalt Thou remove?</p>
    </div>
    <noscript>
        <p>Please enable JavaScript to use this app.</p>
        <!-- or put a simple form for upload here -->
    </noscript>
</div>
{%endblock body%}

templates/poll_base.html
<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    dir="{% if LANGUAGE_BIDI %}rtl{% else %}ltr{% endif %}"
    xml:lang="{% firstof LANGUAGE_CODE 'en' %}"
    lang="{% firstof LANGUAGE_CODE 'en' %}">
  <head>
    <title>{% block title %}{% endblock %} - Image Polling</title>

    <link rel="stylesheet" type="text/css" href="{{MEDIA_URL}}css/ui-lightness/jquery-ui-1.8.16.custom.css">
    <link rel="stylesheet" type="text/css" href="{{MEDIA_URL}}css/imgnotes.css">
    <!-- all in one seo pack 1.4.6.13 [301,360] -->
    <meta name="description" content="Create a free image poll with picpoll.in. Share the poll and let the world know." />
    <meta name="keywords" content="create photo poll,image poll,make photo poll,multimedia poll,photo poll,pic poll,picture poll,polls,post photo poll" />
    <!-- /all in one seo pack -->

    {% block css %}
    {% endblock %}
    <script type="text/javascript">var switchTo5x=false;</script><script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script><script type="text/javascript">stLight.options({publisher:'1b48fe02-6943-4679-8ba7-1b494f5866e2'});</script>
    {% block preload_js %}
    {% endblock %}

    {% block extra-head %}{% endblock %}
  </head>

  <body>
    <div id="header">
      <div style="float:left; position:absolute;">
        <a id="home" href="{%url home %}">Home</a>
        <a id="about" href="{%url about %}">About</a>
      </div>
      <div style="float:right;color:red; margin:0px 10px;">
        <a href="{%url vote_campaign %}" style="color:red;">feeling not to vote?</a>
      </div>
      <!-- info div here -->
      <div >{% block info_div %}{%endblock%}</div>
      <!--Need a nice toolbar-->
    </div>
    <!--ShareButtons-->
    <div style="float:left;">
      <span  class='st_reddit_large' ></span><br /><span  class='st_google_large' ></span><br /><span  class='st_delicious_large' ></span><br /><span  class='st_twitter_large' ></span><br /><span  class='st_facebook_large' ></span><br /><span  class='st_email_large' ></span><br />
    </div>
    {%block body %}{%endblock%}
  </body>
<!--Google analytics code-->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-28557708-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</html>

templates/show_image.html
<!--
TODO:
1. implement delete feature.
2. draggable note.
-->
<script type="text/javascript" src="{{MEDIA_URL}}javascript/jquery-1.6.2.min.js"></script>
<div id="user_image" class="user_image">
  <script type="text/javascript">
    function addOption(){
        $('#tern').imgAreaSelect({ enable:true, onSelectChange: showaddnote, x1: 120, y1: 90, x2: 280, y2: 210 });
        return false;
    }
  function submitUserPoll(){
    url = '{% url submit_poll user_image_id %}'//'/image_polling/submit_poll/{{user_image_id}}/';
    if (Object.keys(notes).length == 0) {
      alert('c\'mon select at least one option for people to vote for.');
      return false;
    }
    if ($("#id_question").val() == 'Thou poll without a question?' || $("#id_question").val().trim() == ''){
      alert('What question should thy ask to the summoned undead? Enter question?')
      return false;
    };
    notes['question'] = $("#id_question").val();
    $.ajax({
      type: 'POST',
      url: url,
      data: notes,
      success: function(data){
        if (data=='success'){
        document.location = '{% url show_poll user_image_id %}'//'/image_polling/{{user_image_id}}'
        }
      },
    });
  }
</script>

  </script>
  </head>
  <body>
  <form style="text-align: center;" id="pollForm">
    <input type="text" class="textbox" id="id_question" name="question" value='Thou poll without a question?' size='100' style="text-align: center;">
  </form>
  <br/>
  <a href="#" id="addnotelink" onclick="javascript:addOption();">Add a note</a>
  <div style="float:right; padding-right:50px; text-align:left; width:450px;">
    <h4>Step Guide for Dummies</h4>
    <ol>
      <li>Good, now that you have very carefully chosen and uploaded a photo. It is time you start asking youself a question about it.<br/>
      <li>Then Carefully chalk out the answers for the question you thought.<br/>
      <li>You know it wouldnt be worth it, but do it for your country.<br/>
      <li>Once you create all the options.<br/>
      <li>Press the tiny button in the corner, Your own poll page will appear.<br/>
      <li>Pat yourself on the back. You just saved the world.<br/>
    </ol>
    <br/>
    <h4>Notes</h4><br/>
    <ul>
      <li>You can delete an option by double clicking on it</li>
      <li>You can add a new option by double clicking on the image you uploaded</li>
    </ul>
  </div>
  <p style="text-align: center;">
  <img id="tern" ondblclick="javascript:addOption()" width="500px" src="/image_polling/user_images/{{user_image_id}}" alt="{{title}}" title="{{title}}">
  <input type="button" value="submit" onclick="submitUserPoll()">
  </p>
  </div>
  <script type="text/javascript">
    var def_text = 'Thou poll without a question?'
    $('#id_question').focus(function(){
        foo = $("#id_question")
        if (foo.val() == def_text){
          foo.val('') 
        }
        });
    $('#id_question').blur(function(){
        foo = $("#id_question")
        if (foo.val() == ''){
          foo.val(def_text)
        }
        });
  </script>
</div>

templates/show_poll.html
{%extends 'poll_base.html' %}
{%block title%}{{ user_image.question }}{%endblock%}
{%block preload_js %}
  <script type="text/javascript" src="{{MEDIA_URL}}javascript/jquery_003.js"></script>
  <script type="text/javascript" src="{{MEDIA_URL}}javascript/jquery-1.6.2.min.js"></script>
  <script type="text/javascript" src="{{MEDIA_URL}}javascript/jquery-ui-1.8.16.custom.min.js"></script>
  <script type="text/javascript" src="{{MEDIA_URL}}javascript/jquery.js"></script>
  <script type="text/javascript" src="{{MEDIA_URL}}javascript/jquery_002.js"></script>
  <script>
    $(window).load(function () {
      notes = {{user_options|safe}}
      $('#user_image').imgNotes()
      $('#user_image').imgAreaSelect({ hide: true, disable:true });
    });
    function voteDaalo(noteObj){
      voting_url = '/image_polling/vote/{{user_image.id}}/'
      $.ajax({
        type: 'POST',
        url: voting_url,
        data: {'vote_option': noteObj.id},
        success: function(data){
          data = jQuery.parseJSON(data)
          if (data['success']){
            $("#info_div").addClass("success")
            $("#info_div").html("Voted successfully")
            $("#options").show()
            $("#options").html("Poll results so far.")
            $("#options").append("<ul>")
            for (i in data['total_votes']){
              $("#options").append("<li>"+i+": "+data['total_votes'][i]+"</li>")
            }
            $("#options").append("</ul>")
          }
          else if (data.error){
            $("#info_div").removeClass();
            $("#info_div").addClass("error")
            $("#info_div").html(data.error)
            $("#options").show()
            $("#options").html("Poll results so far.")
            $("#options").append("<ul>")
            for (i in data['total_votes']){
              $("#options").append("<li>"+i+": "+data['total_votes'][i]+"</li>")
            }
            $("#options").append("</ul>")
          }
          else{
            $("#info_div").html("You were never meant to to see this.")
          }
        },
      });
    }
  </script>
{%endblock preload_js %}
{%block info_div %}
  <div align="center"><div id="info_div" class="validation" style="width:400px;">Please select an option to vote. Do it like you dont know anything</div></div>
{%endblock info_div %}
{%block body %}
    <div>
      <div class="question"><h2 color="black">{{user_image.question}}</h2></div>
        <img id="user_image" width="500px" src="/image_polling/user_images/{{user_image.id}}" alt="{{user_image.question}}" title="{{user_image.question}}">
        <div id="options" style="display; margin:20px">

        </div>
    </div>
{%endblock body %}

templates/vote_or_die.html
{%extends 'poll_base.html' %}
{%block title%}Vote Or Die Campaign{%endblock%}
{%block body %}
<div style="font-size:100%">
  <img src="{{MEDIA_URL}}images/vote_or_die.jpg" width="300px">
    <pre>
      Vote or die motherfucker 
      Motherfucker vote or die 
      Rock the vote or else I'm gonna stick a knife through your eye 

      Democracy is founded on one simple rule 
      Get out there and vote or I will motherfucking kill you 

      I like it when you vote, bitch 
      Shake them titties when you vote, bitch 
      I'll slam my jimmy through your mouth roof 
      Now get your big ass in the polling booth 

      I said vote bitch or I'll fucking kill you 

      Vote or die motherfucker 
      Motherfucker vote or die 
      Can't run from a .38, go ahead and try. 

      Let your opinion be heard 
      You've gotta make a choice 
      Cause after I slit your throat 
      You won't have a fucking voice 

      Vote or Die 
      Vote or Die


      -Sir Shree Shree P. Diddy On Not Voting

      Still think you shouldn't vote??
    </pre>
</div>
{%endblock body %}